### ISSUE TITLE
Schedule Card Question

### ISSUE THREAD

**Issue by gdgeist** [schwartzpub/homeassistant-cards#1]
Thanks for this work!  The schedule card is still throwing an error and my limited review looks like it has issues with the rendering.  Does this leverage another Frontend card?  Travelling for work this week otherwise i would look at it closer.
Also looking to extend to allow for sensors to highlight any missing/late/cheat in the attributes.  The homework card isnt picking out the late/missing and havent had a chance to look at why the 'or' and 'and' parsing of the homework isnt resulting in those showing up.
Again thanks!!!!
![image](https://user-images.githubusercontent.com/13734613/191515830-fef35c82-c666-4c71-ae7c-bc6670209ef2.png)

**Comment by schwartzpub** [comment]
I will take a look at this.  I'll admit I didn't do a whole lot of validation on these cards because it's kind of a pain to test cards in HA after making changes.  I think I only got as far as indicating any assignments that were past due and not marked as submitted (yellow calendar with exclamation), and for at least some cases I know missing attribute was being indicated as well (red calendar with exlamation).

**Comment by schwartzpub** [comment]
> Thanks for this work! The schedule card is still throwing an error and my limited review looks like it has issues with the rendering. Does this leverage another Frontend card? Travelling for work this week otherwise i would look at it closer. Also looking to extend to allow for sensors to highlight any missing/late/cheat in the attributes. The homework card isnt picking out the late/missing and havent had a chance to look at why the 'or' and 'and' parsing of the homework isnt resulting in those showing up. Again thanks!!!! ![image](https://user-images.githubusercontent.com/13734613/191515830-fef35c82-c666-4c71-ae7c-bc6670209ef2.png)

This does not rely on any other cards, though I'm curious if you could check the dev tools in your browser to see if its capturing an error on the schedule card that may narrow down which part of the script is causing the issue.  

I suspect this is where the error is coming from:
`this.term = eTerms.attributes.term.find(t => (this.date >= t.startdate && this.date <= t.enddate)).id`

I'm curious if your terms sensor is getting data.

Another thing to check is if you incremented the card version number in HA -- sometimes you have to increment the version number in the resource in order for HA to reload the card source code.

![image](https://user-images.githubusercontent.com/5823949/191602348-edc91140-c636-4140-8286-ba46faa6a131.png)

**Comment by gdgeist** [comment]
Checking - this is VERY helpful!

**Comment by gdgeist** [comment]
Looks like I got the card to update - new error:

Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at set hass [as hass] (custom-infinitecampus-schedule-card.js:43:105)
    at r.value (cec1ec6d.js:1:9968)
    at r.value (cec1ec6d.js:1:9459)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)
2custom-infinitecampus-schedule-card.js:43 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')
    at set hass [as hass] (custom-infinitecampus-schedule-card.js:43:105)
    at r.value (cec1ec6d.js:1:9830)
    at r.performUpdate (styles.ts:370:1)
    at r.scheduleUpdate (styles.ts:370:1)
    at r._$EC (styles.ts:370:1)

**Comment by gdgeist** [comment]
Term attribute in sensor:
      term:
        id: '92'
        termid: 92
        termscheduleid: 33
        seq: 1
        startdate: '2022-08-29'
        enddate: '2023-01-20'
        termname: S1
        structureid: 45
        isprimary: true
        termschedulename: Semesters
        calendarid: 48
        schedulestructurename: Main

**Comment by gdgeist** [comment]
hopefully SUnday i can spend more time on this - thanks!

**Comment by gdgeist** [comment]
Hunting on this as a type issue from the error and the attribute data:
Error:
custom-infinitecampus-schedule-card.js:43 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'id')


Attribute - id is a string and termid is an integer
id: '92'
termid: 92

**Comment by gdgeist** [comment]
my sensor for terms does not have any attributes beyond friendly name:

![image](https://user-images.githubusercontent.com/13734613/192571431-399e2534-d70a-4765-9b3d-413eac11951b.png)

**Comment by gdgeist** [comment]
thinking keying off of the term id elsewhere for me makes sense - assume this is an artifact of each infinite campus build for each school may be a little different.

**Comment by schwartzpub** [comment]
I would expect there to be terms in your sensor, this sounds like it may be a bug with either the integration or the api client rather than the card.  I'm leaning towards an issue with the integration since it doesn't seem to be populating the sensor during updates or even creating the empty attribute.

**Comment by schwartzpub** [comment]
Can you confirm which version of the integration you're using?
